import { Button, Flex, Link, Separator, Text } from '@radix-ui/themes'
import { ArrowLeftIcon } from '@radix-ui/react-icons'
import useResponsive from '../../hooks/useResponsive'

type BackButtonProps = {
  onClick?: () => void
}

const BackButton = ({ onClick }: BackButtonProps) => (
  <Button variant='ghost' aria-label='Back Button' onClick={onClick}>
    <ArrowLeftIcon />
    BACK
  </Button>
)

const ShorelineChangeSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Shoreline Change
      </Text>
      <Text as='div'>
        The Digital Earth Pacific Shorelines product includes annual shorelines and rates of annual
        change. The product is generated by applying the methods described in Bishop-Taylor et al.
        (2021) to Landsat collection 2 surface reflectance data. It combines this satellite data
        with tidal modelling to estimate the location of the shoreline at mean sea level each year.
        It is currently a beta product generated for the years 1999-2023. However, data may not
        exist prior to 2013 or later for some locations, since Landsat satellite coverage was not
        complete for the Pacific prior to the launch of Landsat 8 in 2013.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        Data Sources
      </Text>
      <Link
        href='https://www.sciencedirect.com/science/article/pii/S0034425721004545'
        target='_blank'
        rel='noopener noreferrer'
        style={{ wordBreak: 'break-all' }}
      >
        https://www.sciencedirect.com/science/article/pii/S0034425721004545
      </Link>
    </Flex>
  </Flex>
)
const HotSpotsSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Hotspots
      </Text>
      <Text as='div'>
        The rates of change product is a point dataset providing rates of coastal change (in metres
        per year) at every 30 m along shorelines. These rates are calculated by performing a linear
        regression between annual shoreline positions and time (year), using the most recent
        shoreline as the baseline. Negative values indicate shoreline retreat/erosion, and positive
        values indicate growth/accretion over time.
      </Text>
      <Text as='div'>
        The hotspots product is derived from the rates of change product. The median value of
        shoreline distance from baseline is computed using all rates of change points within 1km of
        each point. Those showing a significant relationship between these median positions and time
        are retained. The final hotspot product is produced by grouping overlapping hotspots and
        recalculating median values, rates of change, and significance for these groups.
      </Text>
    </Flex>
  </Flex>
)

const PopulationSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Population
      </Text>
      <Text as='div'>
        Population counts represent the estimated total population within all hotspots of the
        selected type within the county, or for the selected hotspot. Counts are based on the best
        available population data and vary by country.
      </Text>
      <Text as='div'>
        Data for Cook Islands, Fiji, Federated States of Micronesia, Kiribati, Marshall Islands,
        Niue, Nauru, Palau, Samoa, Solomon Islands, Tuvalu, Vanuatu, and Wallis and Futuna are from
        the SPC Statistics for Development Division (SDD), obtained from the Pacific Data Hub
        (https://pacificdata.org).
      </Text>
      <Text as='div'>
        Data for American Samoa, Guam, Northern Mariana Islands, New Caledonia, Pitcairn Islands,
        Papua New Guinea, French Polynesia, Tokelau, and Tonga are based on the constrained WorldPop
        HDX spatial distribution of population data for 2025.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        For more information see:
      </Text>
      <Link
        href='https://data.worldpop.org/repo/prj/Global_2015_2030/R2024B/doc/Global2_Release_Statement_R2024B_v1.pdf'
        target='_blank'
        rel='noopener noreferrer'
        style={{ wordBreak: 'break-all' }}
      >
        https://data.worldpop.org/repo/prj/Global_2015_2030/R2024B/doc/Global2_Release_Statement_R2024B_v1.pdf
      </Link>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        Data for Fiji is the experimental GIS Fiji population grid for 2023, obtained from:
      </Text>
      <Link
        href='https://www.statsfiji.gov.fj/experimental-gis-fiji-population-grid-2023/'
        target='_blank'
        rel='noopener noreferrer'
        style={{ wordBreak: 'break-all' }}
      >
        https://www.statsfiji.gov.fj/experimental-gis-fiji-population-grid-2023/
      </Link>
    </Flex>
  </Flex>
)
const BuildingsSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Buildings
      </Text>
      <Text as='div'>
        Buildings data were extracted from OpenStreetMap in August, 2025 and represent all building
        types.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        Data Sources
      </Text>
      <Link href='https://www.openstreetmap.org/' target='_blank' rel='noopener noreferrer'>
        https://www.openstreetmap.org/
      </Link>
    </Flex>
  </Flex>
)
const MangrovesSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Mangroves
      </Text>
      <Text as='div'>
        Mangrove data are from Global Mangrove Watch (version 3) for the year 2020.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        Data Sources
      </Text>
      <Link href='https://zenodo.org/records/6894273' target='_blank' rel='noopener noreferrer'>
        https://zenodo.org/records/6894273
      </Link>
    </Flex>
  </Flex>
)

const RateOfChangeSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Rate of Change
      </Text>
      <Text as='div'>
        The rate of change product is a point dataset providing rates of coastal change (in metres
        per year) at every 30 m along shorelines. These rates are calculated by performing a linear
        regression between annual shoreline positions and time (year), using the most recent
        shoreline as the baseline. Negative values indicate shoreline retreat/erosion, and positive
        values indicate growth/accretion over time. By default, rates of change are only shown for
        points with statistically significant trend over time.
      </Text>
    </Flex>
  </Flex>
)

const BackgroundInformationView = ({ goBackToResultView }: { goBackToResultView: () => void }) => {
  const { isMobileWidth } = useResponsive()
  return (
    <Flex direction='column' gap='4' align='start'>
      <BackButton onClick={goBackToResultView} />
      <Text as='div' size={isMobileWidth ? '6' : '7'} weight='bold'>
        Background Information
      </Text>
      <ShorelineChangeSection />
      <Separator orientation='horizontal' size='4' />
      <HotSpotsSection />
      <Separator orientation='horizontal' size='4' />
      <PopulationSection />
      <Separator orientation='horizontal' size='4' />
      <BuildingsSection />
      <Separator orientation='horizontal' size='4' />
      <MangrovesSection />
      <Separator orientation='horizontal' size='4' />
      <RateOfChangeSection />
    </Flex>
  )
}

export default BackgroundInformationView
