import { Flex, Link, Separator, Text, Callout } from '@radix-ui/themes'
import useResponsive from '../../hooks/useResponsive'
import { BackButton } from '../BackButton'
import styles from './BackgroundInformationView.module.scss'

const CoastlineChangeSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Coastline Change
      </Text>
      <Text as='div'>
        The Digital Earth Pacific Coastlines product includes annual coastlines and rates of annual
        change. The product is generated by applying the methods described in Bishop-Taylor et al.
        (2021) to Landsat collection 2 surface reflectance data. It combines this satellite data
        with tidal modelling to estimate the location of the coastline at mean sea level each year.
        It is currently a beta product generated for the years 1999-2023. However, data may not
        exist prior to 2013 or later for some locations, since Landsat satellite coverage was not
        complete for Pacific Countries and Territories prior to the launch of Landsat 8 in 2013.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        References
      </Text>
      <Link
        href='https://www.sciencedirect.com/science/article/pii/S0034425721004545'
        target='_blank'
        rel='noopener noreferrer'
      >
        https://www.sciencedirect.com/science/article/pii/S0034425721004545
      </Link>
    </Flex>
  </Flex>
)

const HotSpotsSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Hotspots
      </Text>
      <Text as='div'>
        The rates of change product is a point dataset providing rates of coastal change (in metres
        per year) at every 30 m along coastlines. These rates are calculated by performing a linear
        regression between annual coastline positions and time (year), using the most recent
        coastline as the baseline. Negative values indicate coastline retreat/erosion, and positive
        values indicate growth/accretion over time.
      </Text>
      <Text as='div'>
        The depicted hotspot areas are produced by separating rates of change points showing
        significant change and high certainty into three groups: those showing greater than 2 meters
        / year of change, greater than 3 meters / year of change and greater than 5 meters per year
        of change. These points are further separated into those showing coastal retreat and growth.
        Areas shown are within 500-meters of the points in the corresponding category. Where
        locations are within this distance of both growth and retreat points, it is categorized
        based on which type it is closest to.
      </Text>
    </Flex>
  </Flex>
)

const PopulationSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Population
      </Text>
      <Text as='div'>
        Population counts represent the estimated total population within all hotspots of the
        selected type within the county, or for the selected hotspot. Counts are based on the best
        available population data and vary by country.
      </Text>
      <Text as='div'>
        Data for Cook Islands, Fiji, Federated States of Micronesia, Kiribati, Marshall Islands,
        Niue, Nauru, Palau, Samoa, Solomon Islands, Tuvalu, Vanuatu, and Wallis and Futuna are from
        the SPC Statistics for Development Division (SDD), obtained from the Pacific Data Hub (
        <Link href='https://pacificdata.org' target='_blank' rel='noopener noreferrer'>
          https://pacificdata.org
        </Link>
        ).
      </Text>
      <Text as='div'>
        Data for American Samoa, Guam, Northern Mariana Islands, New Caledonia, Pitcairn Islands,
        Papua New Guinea, French Polynesia, Tokelau, and Tonga are based on the constrained WorldPop
        HDX spatial distribution of population data for 2025.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        For more information see:
      </Text>
      <Link
        href='https://data.worldpop.org/repo/prj/Global_2015_2030/R2024B/doc/Global2_Release_Statement_R2024B_v1.pdf'
        target='_blank'
        rel='noopener noreferrer'
        style={{ wordBreak: 'break-all' }}
      >
        https://data.worldpop.org/repo/prj/Global_2015_2030/R2024B/doc/Global2_Release_Statement_R2024B_v1.pdf
      </Link>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        Data for Fiji is the experimental GIS Fiji population grid for 2023, obtained from:
      </Text>
      <Link
        href='https://www.statsfiji.gov.fj/experimental-gis-fiji-population-grid-2023/'
        target='_blank'
        rel='noopener noreferrer'
        style={{ wordBreak: 'break-all' }}
      >
        https://www.statsfiji.gov.fj/experimental-gis-fiji-population-grid-2023/
      </Link>
    </Flex>
  </Flex>
)
const BuildingsSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Buildings
      </Text>
      <Text as='div'>
        Buildings data were extracted from OpenStreetMap in August, 2025 and represent all building
        types.
      </Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        References
      </Text>
      <Link href='https://www.openstreetmap.org/' target='_blank' rel='noopener noreferrer'>
        https://www.openstreetmap.org/
      </Link>
    </Flex>
  </Flex>
)
const MangrovesSection = () => (
  <Flex direction='column' gap='4'>
    <Flex direction='column' gap='2'>
      <Text as='div' size='4' weight='bold'>
        Mangroves
      </Text>
      <Text as='div'>The Mangrove data was produced by Digital Earth Pacific.</Text>
    </Flex>
    <Flex direction='column' gap='2'>
      <Text as='div' weight='bold'>
        References
      </Text>
      <Link
        href='https://digitalearthpacific.org/#/applications'
        target='_blank'
        rel='noopener noreferrer'
      >
        https://digitalearthpacific.org/#/applications
      </Link>
    </Flex>
  </Flex>
)

export const BackgroundInformationView = ({
  goBackToResultView,
}: {
  goBackToResultView: () => void
}) => {
  const { isMobileWidth } = useResponsive()
  return (
    <Flex direction='column' gap='4' align='start'>
      <BackButton onClick={goBackToResultView} />
      <Text as='div' size={isMobileWidth ? '6' : '7'} weight='bold'>
        Background Information
      </Text>
      <Callout.Root size='3' className={styles.backgroundInformationIntroCallout}>
        <Callout.Text>
          Explore how coastlines are changing and potential risks. Your feedback helps us improve
          the data and make this tool even more accurate and valuable for everyone. If you have any
          feedback or suggestions, please get in touch at{' '}
          <Link href='mailto:askdepacific@spc.int'>askdepacific@spc.int</Link>
        </Callout.Text>
      </Callout.Root>
      <Separator orientation='horizontal' size='4' />
      <CoastlineChangeSection />
      <Separator orientation='horizontal' size='4' />
      <HotSpotsSection />
      <Separator orientation='horizontal' size='4' />
      <PopulationSection />
      <Separator orientation='horizontal' size='4' />
      <BuildingsSection />
      <Separator orientation='horizontal' size='4' />
      <MangrovesSection />
    </Flex>
  )
}
