name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          COASTLINE_APP_MAP_TILER_API_KEY: ${{ secrets.MAP_TILER_API_KEY }}

      - name: Add CNAME
        run: "echo dashboards.digitalearthpacific.org > dist/CNAME"

      - name: Upload built files
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: http://dashboards.digitalearthpacific.org/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
